import itertools
import sys
from abc import ABC, abstractmethod
from copy import deepcopy
from enum import Enum
from typing import Any, ClassVar

from abides_core import NanosecondTime
from abides_core.utils import fmt_ts

from .utils import dollarize


class Side(Enum):
    BID = "BID"
    ASK = "ASK"

    def is_bid(self) -> bool:
        return self == Side.BID

    def is_ask(self) -> bool:
        return self == Side.ASK


class TimeInForce(Enum):
    """Time-in-force qualifiers for limit orders.

    - GTC: Good-til-cancelled (default) — rests in the book until filled or
      explicitly cancelled.
    - IOC: Immediate-or-cancel — fills what it can immediately, then the
      unfilled remainder is automatically cancelled (never enters the book).
    - FOK: Fill-or-kill — either the entire order fills immediately or the
      whole order is rejected (never enters the book).
    - DAY: Day order — same as GTC during the trading day, but automatically
      cancelled at market close.
    """

    GTC = "GTC"
    IOC = "IOC"
    FOK = "FOK"
    DAY = "DAY"


class Order(ABC):
    """A basic Order type used by an Exchange to conduct trades or maintain an order book.

    This should not be confused with order Messages agents send to request an Order.
    Specific order types will inherit from this (like LimitOrder).

    Notes:
        ``Order`` and its subclasses use ``__slots__`` for two reasons:

        1. Memory — slotted instances drop the per-instance ``__dict__``,
           saving roughly 280 bytes per order on CPython 3.12. For
           millions of orders in a long simulation this is a measurable
           RSS reduction.
        2. Cheap tuple serialisation — :meth:`to_payload_tuple` reads
           slot values directly without dict construction, which
           unblocks typed Arrow columns in
           :class:`abides_core.parquet_sink.ParquetSink` once consumer
           sites migrate from the legacy ``dict`` payload.

        A consequence is that arbitrary attribute attachment on an
        ``Order`` instance now raises ``AttributeError``. Use the
        ``tag`` field for caller metadata.
    """

    __slots__ = (
        "agent_id",
        "time_placed",
        "symbol",
        "quantity",
        "side",
        "order_id",
        "fill_price",
        "tag",
    )

    # The order_kind sentinel mirrors the discriminator that the
    # ``ORDER_EVENT`` payload schema will eventually carry as a typed
    # column. Subclasses override.
    order_kind: ClassVar[str] = "ORDER"

    _order_id_generator = itertools.count(0)

    @abstractmethod
    def __init__(
        self,
        agent_id: int,
        time_placed: NanosecondTime,
        symbol: str,
        quantity: int,
        side: Side,
        order_id: int | None = None,
        tag: Any = None,
    ) -> None:
        """
        Arguments:
            agent_id: The ID of the agent that created this order.
            time_placed: Time at which the order was created by the agent.
            symbol: Equity symbol for the order.
            quantity: Number of equity units affected by the order.
            side: Indicates if an order is on the BID or ASK side of the market.
            order_id: Either self generated or assigned. Should only be self
            generated by the OrderBook class.
            tag: A free-form user-defined field that can contain any information
                relevant to the entity placing the order.  Recommend keeping it
                alphanumeric rather than shoving in objects, as it will be there
                taking memory for the lifetime of the order and in all logging
                mechanisms.  Intent: for strategy agents to set tags to help keep
                track of the intent of particular orders, to simplify their code.
        """

        self.agent_id: int = agent_id

        self.time_placed: NanosecondTime = time_placed

        self.symbol: str = symbol

        self.quantity: int = quantity

        self.side: Side = side

        if order_id is None:
            order_id = next(Order._order_id_generator)

        self.order_id: int = order_id

        # Create placeholder fields that don't get filled in until certain events happen.
        self.fill_price: int | None = None

        self.tag: Any | None = tag

    def _slot_values(self) -> tuple[Any, ...]:
        """Walk the class MRO collecting every declared slot value.

        Used by :meth:`__eq__` and :meth:`to_dict` as a replacement for
        the pre-slot ``self.__dict__`` snapshot. The walk is
        deterministic: slots are collected in MRO order.
        """
        return tuple(
            getattr(self, name)
            for cls in type(self).__mro__
            for name in getattr(cls, "__slots__", ())
        )

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-friendly snapshot of the order's slot values.

        Replaces the pre-Phase-2a ``deepcopy(self).__dict__`` antipattern.
        The sink contract (sinks must not mutate received payloads)
        makes the defensive copy unnecessary.
        """
        as_dict: dict[str, Any] = {
            name: getattr(self, name)
            for cls in type(self).__mro__
            for name in getattr(cls, "__slots__", ())
        }
        as_dict["time_placed"] = fmt_ts(self.time_placed)
        return as_dict

    @abstractmethod
    def to_payload_tuple(self) -> tuple[Any, ...]:
        """Return a positional tuple matching the ``ORDER_EVENT`` schema.

        Field order (see :mod:`abides_core.event_payloads`):

        ``(order_id, order_kind, symbol, side, quantity, limit_price,
        stop_price, time_in_force, is_hidden, is_price_to_comply,
        tag)``

        Fields not applicable to the concrete subclass are filled with
        ``None``. ``side`` is the :class:`Side` enum and
        ``time_in_force`` is the :class:`TimeInForce` enum (or ``None``
        when not applicable); consumer-side conversion to int / string
        is the sink's responsibility.
        """

    def __eq__(self, other: object) -> bool:
        return (
            type(other) is type(self)
            and self._slot_values() == other._slot_values()  # type: ignore[attr-defined]
        )

    # Orders are mutable (quantity, fill_price, is_hidden change after
    # creation), so equality without a hash matches the pre-Phase-2a
    # contract: instances are unhashable. Defining ``__eq__`` already
    # sets ``__hash__`` to None implicitly.
    __hash__ = None  # type: ignore[assignment]

    def __deepcopy__(self, memodict={}):
        raise NotImplementedError


class LimitOrder(Order):
    """
    LimitOrder class that inherits from Order class and adds a limit price and a
    hidden order flag.

    These are the Orders that typically go in an Exchange's OrderBook.
    """

    __slots__ = (
        "limit_price",
        "is_hidden",
        "is_price_to_comply",
        "insert_by_id",
        "is_post_only",
        "time_in_force",
    )

    order_kind: ClassVar[str] = "LIMIT"

    def __init__(
        self,
        agent_id: int,
        time_placed: NanosecondTime,
        symbol: str,
        quantity: int,
        side: Side,
        limit_price: int,
        is_hidden: bool = False,
        is_price_to_comply: bool = False,
        insert_by_id: bool = False,
        is_post_only=False,
        order_id: int | None = None,
        tag: Any | None = None,
        time_in_force: TimeInForce = TimeInForce.GTC,
    ) -> None:
        super().__init__(
            agent_id, time_placed, symbol, quantity, side, order_id, tag=tag
        )

        # The limit price is the minimum price the agent will accept (for a sell order) or
        # the maximum price the agent will pay (for a buy order).
        self.limit_price: int = limit_price
        self.is_hidden: bool = is_hidden
        self.is_price_to_comply: bool = is_price_to_comply
        self.insert_by_id: bool = insert_by_id
        self.is_post_only: bool = is_post_only
        self.time_in_force: TimeInForce = time_in_force

    def to_payload_tuple(self) -> tuple[Any, ...]:
        return (
            self.order_id,
            self.order_kind,
            self.symbol,
            self.side,
            self.quantity,
            self.limit_price,
            None,
            self.time_in_force,
            self.is_hidden,
            self.is_price_to_comply,
            self.tag,
        )

    def __str__(self) -> str:
        filled = ""
        if self.fill_price:
            filled = f" (filled @ {dollarize(self.fill_price)})"

        # Until we make explicit market orders, we make a few assumptions that EXTREME prices on limit
        # orders are trying to represent a market order.  This only affects printing - they still hit
        # the order book like limit orders, which is wrong.
        return "(Agent {} @ {}{}) : {} {} {} @ {}{}".format(
            self.agent_id,
            fmt_ts(self.time_placed),
            f" [{self.tag}]" if self.tag is not None else "",
            self.side.value,
            self.quantity,
            self.symbol,
            (
                dollarize(self.limit_price)
                if abs(self.limit_price) < sys.maxsize
                else "MKT"
            ),
            filled,
        )

    def __repr__(self) -> str:
        return self.__str__()

    def __deepcopy__(self, memodict={}) -> "LimitOrder":
        tag = None if self.tag is None else deepcopy(self.tag)

        order = LimitOrder(
            self.agent_id,
            self.time_placed,
            self.symbol,
            self.quantity,
            self.side,
            self.limit_price,
            self.is_hidden,
            self.is_price_to_comply,
            self.insert_by_id,
            order_id=self.order_id,
            is_post_only=self.is_post_only,
            tag=tag,
            time_in_force=self.time_in_force,
        )

        order.fill_price = self.fill_price

        return order


class MarketOrder(Order):
    """MarketOrder class, inherits from Order class."""

    __slots__ = ()

    order_kind: ClassVar[str] = "MARKET"

    def __init__(
        self,
        agent_id: int,
        time_placed: NanosecondTime,
        symbol: str,
        quantity: int,
        side: Side,
        order_id: int | None = None,
        tag: Any | None = None,
    ) -> None:
        super().__init__(
            agent_id, time_placed, symbol, quantity, side, order_id=order_id, tag=tag
        )

    def to_payload_tuple(self) -> tuple[Any, ...]:
        return (
            self.order_id,
            self.order_kind,
            self.symbol,
            self.side,
            self.quantity,
            None,
            None,
            None,
            None,
            None,
            self.tag,
        )

    def __str__(self) -> str:
        return f"(Agent {self.agent_id} @ {fmt_ts(self.time_placed)}) : MKT Order {self.side.value} {self.quantity} {self.symbol}"

    def __repr__(self) -> str:
        return self.__str__()

    def __deepcopy__(self, memodict={}) -> "MarketOrder":
        tag = None if self.tag is None else deepcopy(self.tag)

        order = MarketOrder(
            self.agent_id,
            self.time_placed,
            self.symbol,
            self.quantity,
            self.side,
            order_id=self.order_id,
            tag=tag,
        )
        order.fill_price = self.fill_price

        return order


class StopOrder(Order):
    """A stop order that triggers a market order when the last trade price
    crosses the stop price.

    - **Buy stop** (``Side.BID``): triggers when ``last_trade >= stop_price``.
    - **Sell stop** (``Side.ASK``): triggers when ``last_trade <= stop_price``.

    The exchange holds stop orders (they never enter the visible book).
    When triggered, the exchange converts them to a ``MarketOrder`` and
    submits it to the order book.
    """

    __slots__ = ("stop_price",)

    order_kind: ClassVar[str] = "STOP"

    def __init__(
        self,
        agent_id: int,
        time_placed: NanosecondTime,
        symbol: str,
        quantity: int,
        side: Side,
        stop_price: int,
        order_id: int | None = None,
        tag: Any | None = None,
    ) -> None:
        super().__init__(
            agent_id, time_placed, symbol, quantity, side, order_id=order_id, tag=tag
        )
        self.stop_price: int = stop_price

    def to_payload_tuple(self) -> tuple[Any, ...]:
        return (
            self.order_id,
            self.order_kind,
            self.symbol,
            self.side,
            self.quantity,
            None,
            self.stop_price,
            None,
            None,
            None,
            self.tag,
        )

    def __str__(self) -> str:
        return (
            f"(Agent {self.agent_id} @ {fmt_ts(self.time_placed)}) : "
            f"STOP {self.side.value} {self.quantity} {self.symbol} "
            f"@ {dollarize(self.stop_price)}"
        )

    def __repr__(self) -> str:
        return self.__str__()

    def __deepcopy__(self, memodict={}) -> "StopOrder":
        tag = None if self.tag is None else deepcopy(self.tag)

        order = StopOrder(
            self.agent_id,
            self.time_placed,
            self.symbol,
            self.quantity,
            self.side,
            self.stop_price,
            order_id=self.order_id,
            tag=tag,
        )
        order.fill_price = self.fill_price

        return order
